when:
  - event: push
    branch: main
  - event: pull_request
    branch: main

steps:
  - name: build
    image: debian
    commands:
      - echo "This is the build step"
      - echo "binary-data-123" > executable
  - name: a-test-step
    image: python:3.9
    commands:
      - echo "Testing ..."
      - python hello.py